package soqosmw.examples.MinimalEvaluationNetwork.small_network_all_ethernet_protocols;

import core4inet.nodes.ethernet.avb_AS6802.TTEAVBEtherHost;
import core4inet.incoming.AS6802.TTIncoming;
import core4inet.buffer.AS6802.TTQueueBuffer;
import core4inet.incoming.AS6802.RCIncoming;
import core4inet.buffer.AS6802.RCQueueBuffer;
import soqosmw.nodes.SOQoSMWHost;


module SubscriberUDP extends SOQoSMWHost
{
	submodules:
	connections: 
 
}